### ISSUE TITLE
An optional Address field in GatewaySpec and GatewayStatus

### ISSUE THREAD

**Issue by maplain** [kubernetes-sigs/service-apis#137]
**What would you like to be added**:
1. An optional `Address *ListenerAddress` in `GatewaySpec`;
2. An optional `Address *ListenerAddress` in `GatewayStatus`;

**Why is this needed**:
1. `Routes RouteBindingSelector` is defined per `Gateway`, not per `Listener`;
2. `Gateway` represents something more like a `VirtualServer` or `VirtualHost`;
Like James pointed out, it's not uncommon to have a shared IP address per `Gateway`. In that case, it's awkward to duplicate the same `Address` in multiple `Listeners`. The same statement applies to `GatewayStatus` as well.

An optional `Address` in `Gateway` level:
1. makes defaulting to a shared Address easier;
2. adds clarity to the Gateway->Listener hierarchical nature;
3. provides better UX;

@andrewsykim @akutz

**Comment by jpeach** [comment]
A Gateway is a logical configuration that is attached to the network by a Listener. If you collapse that, you change the model quite a lot, and it's not clear to me that there is much of a benefit.

I think that this request would be clearer if there were some user stories associated with it. What configuration scenario does this enable that is not already possible?

**Comment by maplain** [comment]
Thanks @jpeach for your feedback!

This address is optional, so I cannot agree with `you change the model quite a lot`;

> there were some user stories associated with it
> What configuration scenario does this enable that is not already possible
like I said in the description, this adds clarity for use cases like sharing one address per Gateway. I believe you pointed out Contour is one example, but I couldn't find your comment anymore.

For other use cases, it's safe to just omit it to keep the original model.

I guess what's arguable is if we should deliberately keep the Data Model generic(or vague) so different implementations could overload it, or we should clarify the intended usage formally without compromising the existing semantics.

**Comment by hbagdi** [comment]
> In that case, it's awkward to duplicate the same Address in multiple Listeners.

I agree with the awkwardness here.

Currently it is something like this:
```yaml
listeners:
- address: "ip1"
  port: 80
  protocol: tcp
- address: "ip1"
  port: 443
  protocol: tcp
```

Please ignore the values of protocol, that's a separate issue to discuss. And also ignore tls.

I want to propose:

```yaml
```yaml
listeners:
- address: "ip1"
  ports:
  - port: 80
    protocol: tcp
  - port: 443
    protocol: tcp
```

This has come up in a few discussions now. @jpeach @maplain WDYT?
It doesn't address all the concerns of the issue but a part of it.

**Comment by jpeach** [comment]
> On Apr 15, 2020, at 2:03 PM, Harry <notifications@github.com> wrote:
> 
> This has come up in a few discussions now. @jpeach @maplain WDYT?
> It doesn't address all the concerns of the issue but a part of it.

That doesn’t seem unreasonable to me, though I wonder whether we should just file an issue on it and wait until there is implementation experience?

**Comment by yiyangy** [comment]
My question is whether we should simply move Address up one level into Gateway and make it into a list, instead of being part of a listener. 

Spec for the following couple of common use cases would become:

1. HTTP and HTTPS listeners share the same address
```
kind: Gateway
spec:
  addresses:
  - type: IPAddress
    value: 10.1.2.3
  listeners:
  - port: 80
    protocol: HTTP
  - port: 443
    protocol: HTTPS
```
2. Dual stack, IPv4+IPv6
```
kind: Gateway
spec:
  addresses:
  - type: IPAddress
    value: 10.37.0.1
  - type: IPAddress
    value: 2002:a25:1::
  listeners:
  - port: 80
    protocol: HTTP
  - port: 443
    protocol: HTTPS
```
One use case that this change would disallow is to have one Gateway specify multiple load balancers. For example,
```
kind: Gateway
spec:
  listeners:
  - address:
      type: IPAddress
      value: 10.1.2.3
    port: 80
    protocol: HTTP
  - address:
      type: IPAddress
      value: 10.1.2.4
    port: 80
    protocol: HTTP
```
Such configuration might bring ambiguity. For example, instead of static ip, addresses are requested. Then config would become
```
kind: Gateway
spec:
  listeners:
  - port: 80
    protocol: HTTP
  - port: 80
    protocol: HTTP
```
Instead, for this case, we could use a list of Gateways, each representing a load balancer.

Not sure if this change would prevent any use case particular to L4.
