### ISSUE TITLE
Discuss domain match vs. wildcard match for listener hostnames

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#206]
In #193, we define a "Domain" match type to match a set of hostnames to a single domain name. The semantics of matching the "example.com" domain are the same as matching a TLS wildcard of "*.example.com" (i.e. a single leftmost domain label is wild).

In #193 there was some discussion that "wildcard" terminology was easier to understand. So we could consider changing this:
```yaml
hostname:
  match: Domain
  name: example.com
```

to this:
```yaml
hostname:
  match: Wildcard
  name: *.example.com
```
