### ISSUE TITLE
namespaceSelector wrong in Gateway examples?

### ISSUE THREAD

**Issue by SantoDE** [kubernetes-sigs/service-apis#230]
**What happened**:
Tried to apply the current examples on a k3d.

```
error: error validating "service_api.yaml": error validating data: [ValidationError(Gateway.spec.listeners[0].routes): unknown field "namespaceSelector" in io.x-k8s.networking.v1alpha1.Gateway.spec.listeners.routes, ValidationError(Gateway.spec.listeners[1].routes): unknown field "namespaceSelector" in io.x-k8s.networking.v1alpha1.Gateway.spec.listeners.routes]; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
That it works ;-)

**How to reproduce it (as minimally and precisely as possible)**:
Try to apply the examples.

**Anything else we need to know?**:
I figured that a definition like

```
  - protocol: HTTP
    routes:
      routeNamespaces:
        namespaceSelector: {}
      routeSelector:
        matchLabels:
          "controller": "traefik"
  - protocol: HTTPS
```

works. Now my question is, are the examples out-of-date or is there something wrong with the spec? To me, it looks like "old" examples but I wanna confirm here first. :-)
