### ISSUE TITLE
Rename GatewayClassName Field to GatewayClass

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#356]
**What would you like to be added**:
Rename `GatewayClassName` field to `GatewayClass` in `Gateway` API.

**Why is this needed**:
Brevity and a `GatewayClass` is cluster-scoped so it can be implied that `GatewayClass` is a name and not a namespaced name.

__Current:__
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-gateway
  namespace: default
spec:
  gatewayClassName: acme-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: UDP
    port: 8080
    routes:
      resource: udpproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          "app": "foo"
``` 

__Proposed:___
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-gateway
  namespace: default
spec:
  gatewayClass: acme-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: UDP
    port: 8080
    routes:
      resource: udpproutes
      routeNamespaces:
        namespaceSelector: {}
        onlySameNamespace: false
      routeSelector:
        matchLabels:
          "app": "foo"
```
