### ISSUE TITLE
Simplify Gateway Route Selection

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#363]
This is a follow up to https://github.com/kubernetes-sigs/service-apis/pull/362.

A listener currently looks like this:
```
  - protocol: HTTP
    port: 80
    routes:
      resource: httproutes
      routeNamespaces:
        from: "Selector"
        selector: {}
      routeSelector:
        matchLabels:
          app: foo
```

I'm interested in the possibility of simplifying that to:

```
  - protocol: HTTP
    port: 80
    routes:
      resource: httproutes
      namespaces:
        from: "Selector"
        selector: {}
      selector:
        matchLabels:
          app: foo
```

The two selectors being so close to each other feels potentially confusing. On the other hand, the standard case becomes much simpler:

```
  - protocol: HTTP
    port: 80
    routes:
      resource: httproutes
      selector:
        matchLabels:
          app: foo
```
