### ISSUE TITLE
RegExp and capture group in host entry, usable to target headless services

### ISSUE THREAD

**Issue by suvl** [kubernetes-sigs/service-apis#37]
I've been redirected here coming [from this issue](https://github.com/kubernetes/kubernetes/issues/86132).

I have some `StatefulSet` that is accessible through a headless service. Then I want to target each specific instance of that service (clients would know what service from a redirect request). That service would have N instances at any given time.

It's something like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice
  namespace: somens
spec:
  rules:
  - host: ~^baseaddr-(?<srv_host>\d+)\.example\.com$
    http:
      paths:
      - backend:
          serviceName: myservice-$srv_host.myservice.somens
          servicePort: 80
```

I ended up just changing the `nginx-template` and added hard-coded `server` entries for all my cases, but it feels quite hacky. And it only works with nginx, ofc.

So I'm here to present this use-case for your analysis.
