### ISSUE TITLE
Upstream protocol cannot be defined

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#396]
**What happened**:

I was trying to define a set of manifests to use HTTPS between the Gateway and backend:
```yaml
kind: BackendPolicy
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-app
spec:
  backendRefs:
  - name: my-service
    group: core
    kind: Service
    port: 8443
  tls:
    clientCertificateRef: {}
    certificateAuthorityRef:
      name: my-cluster-ca
      group: core
      kind: Secret
    options: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    app: my-service
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-service-route
spec:
  hostnames:
  - "foo.com"
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    forwardTo:
    - serviceName: my-service1
      port: 8443
```

There is no place to define the protocol the Gateway should use to talk to the upstream. The above info is also not sufficient to determine it. This also applies to protocols like TCP/TLS.

**What you expected to happen**:

There should be a way to define upstream protocol to use.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
