### ISSUE TITLE
Gateway listeners default for HostnameMatch

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#403]
**What happened**:
I was trying to use a Gateway for protocols without a concept of "hostname".
The HostnameMatch field in Gateway defaults to `match: any` which is ambiguous. 

**What you expected to happen**:

One should be able to use protocols that don't have the concept of hostnames.

**How to reproduce it (as minimally and precisely as possible)**:

```
  listeners:
  - hostname:
      match: Any
    port: 8080
    protocol: TCP
    routes:
      group: networking.x-k8s.io
      kind: TCPRoute
      routeNamespaces:
        from: All
      routeSelector:
        matchLabels:
          app: foo
```

**Anything else we need to know?**:

**Comment by hbagdi** [comment]
We have two options:
- Make HostnameMatch optional and do NOT default
- Introduce a match type of None (seems wrong)

**Comment by jpeach** [comment]
The default is `{match: "Any"}` which matches everything.

Docs say:
>         // If a match type other than "Any" is supplied, it MUST
>        // be compatible with the specified Protocol field.

>        // HostnameMatchAny specifies that this Listener accepts
>        // all client traffic regardless of the presence or value of
>        // any hostname supplied by the client.

So it sounds like "Any" is what you want here?

**Comment by hbagdi** [comment]
Yes, the docs do cover that but as a user studying/working with YAML, that's not obvious when the user is not even thinking about the hostname.

**Comment by jpeach** [comment]
> Yes, the docs do cover that but as a user studying/working with YAML, that's not obvious when the user is not even thinking about the hostname.

IIUC you don't have to specify it, the defaulting sets it if you don't.

**Comment by hbagdi** [comment]
> IIUC you don't have to specify it, the defaulting sets it if you don't.

That's right. My concern is that it is the end state that doesn't make much sense for the user and has the potential to confuse users and maintainers.

**Comment by jpeach** [comment]
> > IIUC you don't have to specify it, the defaulting sets it if you don't.
> 
> That's right. My concern is that it is the end state that doesn't make much sense for the user and has the potential to confuse users and maintainers.

I don't really follow that since you could make the same argument about any sort of defaulting. The alternative to explicit defaulting is for each controller to internally apply defaulting which is invisible to the operator.

**Comment by danehans** [comment]
What about this approach:
```
listeners:
  - port: 8080
    protocol:
      type: HTTP
      hostnameMatch: any
    routes:
      group: networking.x-k8s.io
      kind: TCPRoute
      routeNamespaces:
        from: All
      routeSelector:
        matchLabels:
          app: foo
```
`hostnameMatch` would be ignored for TCP protocol type.
