### ISSUE TITLE
Add Support for Per Target Filters

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#55]
**What would you like to be added**:
The ability to apply filters after a forwardTo action of an `HTTPRoute`. 

**Why is this needed**:
Several proxy implementations support the ability to modify requests after making a forwarding decision.

From a sketch api [comment](https://docs.google.com/document/d/1BxYbDovMwnEqe8lj8JwHo8YxHAt3oC7ezhlFsG_tyag/edit?disco=AAAADsbvEx4):

"This would allow the usage in which traffic can be split among the same backend, but with additional information added to the request (a canary flag, for example).

Knative 0-to-1 scaling is handled by a single Activator backend, and in the case of traffic split among different versions of the same app, the Activator backend needs to know which app to activate through the instrumentation of additional headers."

**Comment by tcnghia** [comment]
An example of this use case looks like this

```
kind: HTTPRoute
name: http-app
rules:
- match:
    host: ...
  action:
    backend:
      splits:
      - percent: 50
        name: activator-or-revision-1-service
        modifier:
          rewriteHeader:
            Knative-Serving-Revision: http-app-revision-1
      - percent: 50
        name: activator-or-revision-1-service
        modifier:
          rewriteHeader:
            Knative-Serving-Revision: http-app-revision-2
```
